export const typePalettesMid = {
   fire: "bg-red-600",
   water: "bg-blue-600",
   grass: "bg-green-600",
   normal: "bg-gray-600",
   fighting: "bg-amber-600",
   flying: "bg-sky-400",
   poison: "bg-purple-600",
   ground: "bg-yellow-800",
   rock: "bg-stone-500",
   bug: "bg-lime-700",
   ghost: "bg-purple-800",
   steel: "bg-zinc-400",
   electric: "bg-yellow-500",
   psychic: "bg-pink-500",
   ice: "bg-cyan-500",
   dragon: "bg-indigo-500",
   dark: "bg-slate-600",
   fairy: "bg-fuchsia-400"
}

export const typePalettesHover = {
   fire: "hover:bg-red-500",
   water: "hover:bg-blue-500",
   grass: "hover:bg-green-500",
   normal: "hover:bg-gray-500",
   fighting: "hover:bg-amber-500",
   flying: "hover:bg-sky-500",
   poison: "hover:bg-indigo-500",
   ground: "hover:bg-yellow-900",
   rock: "hover:bg-stone-500",
   bug: "hover:bg-lime-500",
   ghost: "hover:bg-violet-500",
   steel: "hover:bg-zinc-500",
   electric: "hover:bg-yellow-500",
   psychic: "hover:bg-fuchsia-500",
   ice: "hover:bg-cyan-500",
   dragon: "hover:bg-indigo-600",
   dark: "hover:bg-slate-500",
   fairy: "hover:bg-pink-500"
}

export const typePalettesDark = {
   fire: "bg-red-900",
   water: "bg-blue-700",
   grass: "bg-green-700",
   normal: "bg-gray-700",
   fighting: "bg-amber-700",
   flying: "bg-sky-700",
   poison: "bg-indigo-700",
   ground: "bg-orange-950",
   rock: "bg-stone-700",
   bug: "bg-lime-700",
   ghost: "bg-violet-700",
   steel: "bg-zinc-700",
   electric: "bg-yellow-700",
   psychic: "bg-fuchsia-700",
   ice: "bg-cyan-700",
   dragon: "bg-purple-700",
   dark: "bg-slate-700",
   fairy: "bg-pink-50"
}

export const typesGradientStart = {
  fire: "from-red-500",
  water: "from-blue-500",
  grass: "from-green-500",
  normal: "from-gray-400",
  fighting: "from-amber-500",
  flying: "from-sky-500",
  poison: "from-purple-600",
  ground: "from-yellow-800",
  rock: "from-stone-500",
  bug: "from-lime-500",
  ghost: "from-violet-500",
  steel: "from-zinc-500",
  electric: "from-yellow-400",
  psychic: "from-pink-500",
  ice: "from-cyan-400",
  dragon: "from-indigo-500",
  dark: "from-slate-500",
  fairy: "from-fuchsia-500"
}

export const typesGradientEnd = {
  fire: "to-red-500",
  water: "to-blue-500",
  grass: "to-green-500",
  normal: "to-gray-500",
  fighting: "to-amber-600",
  flying: "to-sky-500",
  poison: "to-purple-700",
  ground: "to-amber-800",
  rock: "to-stone-500",
  bug: "to-lime-600",
  ghost: "to-purple-300",
  steel: "to-zinc-400",
  electric: "to-yellow-500",
  psychic: "to-fuchsia-500",
  ice: "to-cyan-500",
  dragon: "to-indigo-500",
  dark: "to-slate-800",
  fairy: "to-fuchsia-400"
}

export const typesGradientDouble = {
  fire: "to-amber-700",
  water: "to-indigo-950",
  grass: "to-green-800",
  normal: "to-gray-500",
  fighting: "to-yellow-600",
  flying: "to-sky-700",
  poison: "to-pink-900",
  ground: "to-orange-800",
  rock: "to-stone-400",
  bug: "to-lime-700",
  ghost: "to-slate-700",
  steel: "to-zinc-700",
  electric: "to-yellow-700",
  psychic: "to-fuchsia-900",
  ice: "to-cyan-200",
  dragon: "to-fuchsia-700",
  dark: "to-slate-900",
  fairy: "to-fuchsia-300"
}

export const typesBorder = {
  fire: "border-red-700",
  water: "border-blue-700",
  grass: "border-green-700",
  normal: "border-gray-500",
  fighting: "border-amber-700",
  flying: "border-sky-700",
  poison: "border-purple-700",
  ground: "border-yellow-900",
  rock: "border-stone-700",
  bug: "border-lime-700",
  ghost: "border-violet-700",
  steel: "border-zinc-700",
  electric: "border-yellow-700",
  psychic: "border-pink-600",
  ice: "border-cyan-500",
  dragon: "border-purple-700",
  dark: "border-slate-700",
  fairy: "border-fuchsia-500"
}

export const typesBorderHover = {
  fire: "hover:border-red-600",
  water: "hover:border-blue-600",
  grass: "hover:border-green-600",
  normal: "hover:border-gray-400",
  fighting: "hover:border-zinc-600",
  flying: "hover:border-sky-600",
  poison: "hover:border-purple-600",
  ground: "hover:border-yellow-900",
  rock: "hover:border-stone-600",
  bug: "hover:border-lime-600",
  ghost: "hover:border-violet-600",
  steel: "hover:border-zinc-600",
  electric: "hover:border-yellow-600",
  psychic: "hover:border-fuchsia-600",
  ice: "hover:border-cyan-600",
  dragon: "hover:border-purple-600",
  dark: "hover:border-slate-600",
  fairy: "hover:border-fuchsia-600"
}